### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by jurca** [m59peacemaker/browser-insular-observer#1]
Hello,

would you be willing to support TypeScript ecosystem? There are various options, however, I think it would be best for future maintainability to port the code to TypeScript instead of adding separate type declaration files.

I am willing to do all the work myself and send a pull request.

Would that be OK with you, or would you rather go for a different option?

**Comment by m59peacemaker** [comment]
I like Typescript and agree with your thinking. A PR would be great. Thanks!

**Comment by jurca** [comment]
Great, I start working on this once https://github.com/TehShrike/key-master/issues/8 and https://github.com/lovasoa/rectangle-overlap/issues/1 is done, thanks!

**Comment by jurca** [comment]
Hello, sorry it took so long (communication was slow at moments while working on the before-mentioned packages), here is the PR: https://github.com/m59peacemaker/browser-insular-observer/pull/2

**Comment by m59peacemaker** [comment]
It turns out that the tests were passing, but some assertions were being skipped. I'll investigate soon.

**Comment by m59peacemaker** [comment]
Tests fixed and published as v0.1.0 with your TS support.

**Comment by jurca** [comment]
That's awesome, thanks a lot!
