### ISSUE TITLE
The published package is broken

### ISSUE THREAD

**Issue by jurca** [m59peacemaker/browser-insular-observer#3]
Hi,

first, sorry it took me this long to notice, I was occupied elsewhere.

It appears that the package published to the npm registry does not include the `dist` directory, making it unusable.

I did a dry run on `npm publish` to see if we have misconfigured something, but everything seems fine:

```
npm notice 📦  insular-observer@0.1.0
npm notice === Tarball Contents === 
npm notice 6.6kB LICENSE            
npm notice 1.2kB dist/index.js      
npm notice 1.4kB package.json       
npm notice 887B  dist/index.d.ts.map
npm notice 1.2kB dist/index.js.map  
npm notice 2.2kB README.md          
npm notice 1.1kB dist/index.d.ts    
npm notice 2.3kB index.ts           
npm notice 218B  .travis.yml        
npm notice === Tarball Details === 
npm notice name:          insular-observer                        
npm notice version:       0.1.0                                   
npm notice package size:  5.9 kB                                  
npm notice unpacked size: 17.1 kB                                 
npm notice shasum:        b367770edaaccd55de44e505558d6976184cf66f
npm notice integrity:     sha512-ddHVnBnhOxCAf[...]En55Q0kOhTLgQ==
npm notice total files:   9                                       
npm notice
```

Could you please look into this? Please try running `npm publish --dry-run` yourself first to see if the `dist` directory would be included if publishing from your machine. Also - are you using npm or yarn? If you're using yarn to publish the package, I'm guessing yarn might not be compatible with some aspect of our setup here.

**Comment by m59peacemaker** [comment]
Interesting. I have no idea how that could be published without dist/. I like to keep dist/ in my repos anyway, so I happened to put it back before publishing, but I'm pretty sure that just publishing again would have worked without that. :man_shrugging: Thanks for pointing this out. I installed 0.1.1 and confirmed it does have dist/.

**Comment by jurca** [comment]
Thank you for fixing this! :tada:
